//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcmage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arbitro : Utilizador
    {
        public Arbitro()
        {
            this.Jogo = new HashSet<Jogo>();
        }
    
        public string Nome { get; set; }
        public string Avatar { get; set; }
    
        public virtual ICollection<Jogo> Jogo { get; set; }
    }
}
