//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcmage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carta
    {
        public Carta()
        {
            this.Deck = new HashSet<Deck>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Facao { get; set; }
        public string Tipo { get; set; }
        public string Custo { get; set; }
        public int Lealdade { get; set; }
        public string Texto { get; set; }
        public Nullable<int> Ataque { get; set; }
        public Nullable<int> Defesa { get; set; }
    
        public virtual ICollection<Deck> Deck { get; set; }
    }
}
