//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcmage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModeloContainer : DbContext
    {
        public DataModeloContainer()
            : base("name=Data_x0020_ModeloContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Utilizador> UtilizadorSet { get; set; }
        public DbSet<Torneio> TorneioSet { get; set; }
        public DbSet<Jogo> JogoSet { get; set; }
        public DbSet<Deck> DeckSet { get; set; }
        public DbSet<Carta> CartaSet { get; set; }
        public DbSet<Equipa> EquipaSet { get; set; }
        public DbSet<Jogador> JogadorSet { get; set; }
    }
}
