//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcmage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deck
    {
        public Deck()
        {
            this.JogoDeck1 = new HashSet<Jogo>();
            this.JogoDeck2 = new HashSet<Jogo>();
            this.Carta = new HashSet<Carta>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Jogo> JogoDeck1 { get; set; }
        public virtual ICollection<Jogo> JogoDeck2 { get; set; }
        public virtual ICollection<Carta> Carta { get; set; }
    }
}
