//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcmage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipa
    {
        public Equipa()
        {
            this.JogoEquipa1 = new HashSet<JogoEquipa>();
            this.JogoEquipa2 = new HashSet<JogoEquipa>();
            this.TorneioEquipa = new HashSet<TorneioEquipa>();
            this.Jogador = new HashSet<Jogador>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Avatar { get; set; }
    
        public virtual ICollection<JogoEquipa> JogoEquipa1 { get; set; }
        public virtual ICollection<JogoEquipa> JogoEquipa2 { get; set; }
        public virtual ICollection<TorneioEquipa> TorneioEquipa { get; set; }
        public virtual ICollection<Jogador> Jogador { get; set; }
    }
}
