//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcmage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogador
    {
        public Jogador()
        {
            this.TorneioNormal = new HashSet<TorneioNormal>();
            this.Equipa = new HashSet<Equipa>();
            this.JogoNormal1 = new HashSet<JogoNormal>();
            this.JogoNormal2 = new HashSet<JogoNormal>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public int Idade { get; set; }
        public string Avatar { get; set; }
    
        public virtual ICollection<TorneioNormal> TorneioNormal { get; set; }
        public virtual ICollection<Equipa> Equipa { get; set; }
        public virtual ICollection<JogoNormal> JogoNormal1 { get; set; }
        public virtual ICollection<JogoNormal> JogoNormal2 { get; set; }
    }
}
