//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcmage
{
    using System;
    using System.Collections.Generic;
    
    public partial class JogoEquipa : Jogo
    {
    
        public virtual Equipa Equipa1 { get; set; }
        public virtual Equipa Equipa2 { get; set; }
        public virtual TorneioEquipa TorneioEquipa { get; set; }
    }
}
