//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcmage
{
    using System;
    using System.Collections.Generic;
    
    public partial class JogoNormal : Jogo
    {
    
        public virtual TorneioNormal TorneioNormal { get; set; }
        public virtual Jogador Jogador1 { get; set; }
        public virtual Jogador Jogador2 { get; set; }
    }
}
