//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcmage
{
    using System;
    using System.Collections.Generic;
    
    public partial class TorneioNormal : Torneio
    {
        public TorneioNormal()
        {
            this.JogoNormal = new HashSet<JogoNormal>();
            this.Jogador = new HashSet<Jogador>();
        }
    
    
        public virtual ICollection<JogoNormal> JogoNormal { get; set; }
        public virtual ICollection<Jogador> Jogador { get; set; }
    }
}
