//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcmage
{
    using System;
    using System.Collections.Generic;
    
    public partial class TorneioEquipa : Torneio
    {
        public TorneioEquipa()
        {
            this.JogoEquipa = new HashSet<JogoEquipa>();
            this.Equipa = new HashSet<Equipa>();
        }
    
    
        public virtual ICollection<JogoEquipa> JogoEquipa { get; set; }
        public virtual ICollection<Equipa> Equipa { get; set; }
    }
}
